<?php

namespace App\Http\Resources;

use Illuminate\Http\Resources\Json\JsonResource;

class StatBlockResource extends JsonResource
{
    public function toArray($request)
    {
        return [
            'id'                     => $this->id,
            'user_id'                => optional($this->user)->id,
            'team_id'                => optional($this->team)->id,
            'name'                   => $this->name,
            'size'                   => $this->size,
            'stat_block_type'        => $this->statBlockType,
            'type'                   => $this->type,
            'subtype'                => $this->subtype,
            'alignment'              => $this->alignment,
            'armor_class'            => $this->armorClass,
            'hit_points'             => $this->hit_points,
            'hit_dice'               => $this->hit_dice,
            'speed'                  => $this->speed,
            'strength'               => $this->strength,
            'dexterity'              => $this->dexterity,
            'constitution'           => $this->constitution,
            'intelligence'           => $this->intelligence,
            'wisdom'                 => $this->wisdom,
            'charisma'               => $this->charisma,
            'strength_save'          => $this->strengthSave,
            'dexterity_save'         => $this->dexteritySave,
            'constitution_save'      => $this->constitutionSave,
            'intelligence_save'      => $this->intelligenceSave,
            'wisdom_save'            => $this->wisdomSave,
            'charisma_save'          => $this->charismaSave,
            'acrobatics'             => $this->acrobatics,
            'animal_handling'        => $this->animalHandling,
            'arcana'                 => $this->arcana,
            'athletics'              => $this->athletics,
            'deception'              => $this->deception,
            'history'                => $this->history,
            'insight'                => $this->insight,
            'intimidation'           => $this->intimidation,
            'investigation'          => $this->investigation,
            'medicine'               => $this->medicine,
            'nature'                 => $this->nature,
            'perception'             => $this->perception,
            'performance'            => $this->performance,
            'persuasion'             => $this->persuasion,
            'religion'               => $this->religion,
            'sleight_of_hand'        => $this->sleightOfHand,
            'stealth'                => $this->stealth,
            'survival'               => $this->survival,
            'damage_immunities'      => $this->damageImmunities,
            'damage_resistances'     => $this->damageResistances,
            'damage_vulnerabilities' => $this->damageVulnerabilities,
            'condition_immunities'   => $this->conditionImmunities,
            'senses'                 => $this->senses,
            'languages'              => $this->languages,
            'challenge_rating'       => $this->challengeRating,
            'legendary_description'  => $this->legendaryDescription,
            'speed_json'             => $this->speedJson,
            'armor_description'      => $this->armorDescription,
            'collection'             => $this->collection,
            'created_at'             => $this->createdAt,
            'updated_at'             => $this->updatedAt,
            'experience_points'      => $this->experiencePoints,
            'initiative'             => $this->initiative,
            'strength_modifier'      => $this->strengthModifier,
            'dexterity_modifier'     => $this->dexterityModifier,
            'constitution_modifier'  => $this->constitutionModifier,
            'intelligence_modifier'  => $this->intelligenceModifier,
            'wisdom_modifier'        => $this->wisdomModifier,
            'charisma_modifier'      => $this->charismaModifier,
            'actions'                => $this->actions->toArray(),
            'legendary_actions'      => $this->legendaryActions,
            'reactions'              => $this->reactions->toArray(),
            'special_abilities'      => $this->specialAbilities,
        ];
    }
}
